// Seed data for the Hanzi Movie Method database
// This file contains initial data that can be imported into the app

export interface SeedCharacter {
  traditional: string;
  simplified: string;
  pinyin: string;
  definition: string;
}

// Characters from chars.md
export const seedCharacters: SeedCharacter[] = [
  { traditional: "一", simplified: "一", pinyin: "yī", definition: "one" },
  { traditional: "在", simplified: "在", pinyin: "zài", definition: "in, at, on" },
  { traditional: "有", simplified: "有", pinyin: "yǒu", definition: "have, possess" },
  { traditional: "個", simplified: "个", pinyin: "gè", definition: "piece, item" },
  { traditional: "我", simplified: "我", pinyin: "wǒ", definition: "I, me" },
  { traditional: "不", simplified: "不", pinyin: "bù", definition: "not, no" },
  { traditional: "這", simplified: "这", pinyin: "zhè", definition: "this" },
  { traditional: "他", simplified: "他", pinyin: "tā", definition: "he, him" },
  { traditional: "也", simplified: "也", pinyin: "yě", definition: "also, too" },
  { traditional: "就", simplified: "就", pinyin: "jiù", definition: "then, at once" },
  { traditional: "人", simplified: "人", pinyin: "rén", definition: "person, people" },
  { traditional: "都", simplified: "都", pinyin: "dōu", definition: "all, even" },
  { traditional: "說", simplified: "说", pinyin: "shuō", definition: "speak, talk" },
  { traditional: "而", simplified: "而", pinyin: "ér", definition: "and yet" },
  { traditional: "們", simplified: "们", pinyin: "men", definition: "plural marker" },
  { traditional: "你", simplified: "你", pinyin: "nǐ", definition: "you" },
  { traditional: "了", simplified: "了", pinyin: "le", definition: "particle: completed action" },
  { traditional: "要", simplified: "要", pinyin: "yào", definition: "want, need, must" },
  { traditional: "會", simplified: "会", pinyin: "huì", definition: "can, will, to meet" },
  { traditional: "對", simplified: "对", pinyin: "duì", definition: "correct, toward" },
  { traditional: "和", simplified: "和", pinyin: "hé", definition: "and, with" },
  { traditional: "以", simplified: "以", pinyin: "yǐ", definition: "using, because of" },
  { traditional: "很", simplified: "很", pinyin: "hěn", definition: "very" },
  { traditional: "的", simplified: "的", pinyin: "de", definition: "possessive particle" },
  { traditional: "大", simplified: "大", pinyin: "dà", definition: "big, great" },
  { traditional: "能", simplified: "能", pinyin: "néng", definition: "can, able" },
  { traditional: "她", simplified: "她", pinyin: "tā", definition: "she, her" },
  { traditional: "那", simplified: "那", pinyin: "nà", definition: "that" },
  { traditional: "上", simplified: "上", pinyin: "shàng", definition: "on, above" },
  { traditional: "但", simplified: "但", pinyin: "dàn", definition: "but, yet" },
  { traditional: "年", simplified: "年", pinyin: "nián", definition: "year" },
  { traditional: "還", simplified: "还", pinyin: "hái", definition: "still, yet" },
  { traditional: "最", simplified: "最", pinyin: "zuì", definition: "most" },
  { traditional: "為", simplified: "为", pinyin: "wéi", definition: "for, because" },
  { traditional: "來", simplified: "来", pinyin: "lái", definition: "come, arrive" },
  { traditional: "所", simplified: "所", pinyin: "suǒ", definition: "that which" },
  { traditional: "兩", simplified: "两", pinyin: "liǎng", definition: "two, both" },
  { traditional: "可", simplified: "可", pinyin: "kě", definition: "can, may" },
  { traditional: "好", simplified: "好", pinyin: "hǎo", definition: "good" },
  { traditional: "等", simplified: "等", pinyin: "děng", definition: "etc., wait" },
  { traditional: "又", simplified: "又", pinyin: "yòu", definition: "again" },
  { traditional: "將", simplified: "将", pinyin: "jiāng", definition: "be about to" },
  { traditional: "從", simplified: "从", pinyin: "cóng", definition: "from, since" },
  { traditional: "更", simplified: "更", pinyin: "gèng", definition: "more, even more" },
  { traditional: "被", simplified: "被", pinyin: "bèi", definition: "by (passive)" },
  { traditional: "才", simplified: "才", pinyin: "cái", definition: "only then" },
  { traditional: "已", simplified: "已", pinyin: "yǐ", definition: "already" },
  { traditional: "每", simplified: "每", pinyin: "měi", definition: "every" },
  { traditional: "次", simplified: "次", pinyin: "cì", definition: "time, order" },
  { traditional: "把", simplified: "把", pinyin: "bǎ", definition: "object marker" },
  { traditional: "三", simplified: "三", pinyin: "sān", definition: "three" },
  { traditional: "讓", simplified: "让", pinyin: "ràng", definition: "allow, let" },
  { traditional: "做", simplified: "做", pinyin: "zuò", definition: "make, do" },
  { traditional: "再", simplified: "再", pinyin: "zài", definition: "again" },
  { traditional: "只", simplified: "只", pinyin: "zhǐ", definition: "only" },
  { traditional: "卻", simplified: "却", pinyin: "què", definition: "however, but" },
  { traditional: "想", simplified: "想", pinyin: "xiǎng", definition: "think, want" },
  { traditional: "去", simplified: "去", pinyin: "qù", definition: "go" },
  { traditional: "到", simplified: "到", pinyin: "dào", definition: "arrive, reach" },
  { traditional: "看", simplified: "看", pinyin: "kàn", definition: "see, look at" },
  { traditional: "小", simplified: "小", pinyin: "xiǎo", definition: "small, little" },
  { traditional: "天", simplified: "天", pinyin: "tiān", definition: "sky, heaven, day" },
  { traditional: "新", simplified: "新", pinyin: "xīn", definition: "new" },
  { traditional: "中", simplified: "中", pinyin: "zhōng", definition: "middle, center" },
  { traditional: "使", simplified: "使", pinyin: "shǐ", definition: "make, cause" },
  { traditional: "全", simplified: "全", pinyin: "quán", definition: "all, whole" },
  { traditional: "高", simplified: "高", pinyin: "gāo", definition: "tall, high" },
  { traditional: "如", simplified: "如", pinyin: "rú", definition: "like, as if" },
  { traditional: "元", simplified: "元", pinyin: "yuán", definition: "yuan, first" },
  { traditional: "用", simplified: "用", pinyin: "yòng", definition: "use" },
  { traditional: "先", simplified: "先", pinyin: "xiān", definition: "first, before" },
  { traditional: "地", simplified: "地", pinyin: "dì", definition: "earth, ground" },
  { traditional: "給", simplified: "给", pinyin: "gěi", definition: "give" },
  { traditional: "月", simplified: "月", pinyin: "yuè", definition: "moon, month" },
  { traditional: "名", simplified: "名", pinyin: "míng", definition: "name" },
  { traditional: "比", simplified: "比", pinyin: "bǐ", definition: "compare" },
  { traditional: "常", simplified: "常", pinyin: "cháng", definition: "often" },
  { traditional: "走", simplified: "走", pinyin: "zǒu", definition: "walk, go" },
  { traditional: "當", simplified: "当", pinyin: "dāng", definition: "when, act as" },
  { traditional: "問", simplified: "问", pinyin: "wèn", definition: "ask" },
  { traditional: "講", simplified: "讲", pinyin: "jiǎng", definition: "speak, explain" },
  { traditional: "沒", simplified: "没", pinyin: "méi", definition: "not have" },
  { traditional: "話", simplified: "话", pinyin: "huà", definition: "words, speech" },
  { traditional: "真", simplified: "真", pinyin: "zhēn", definition: "really, true" },
  { traditional: "六", simplified: "六", pinyin: "liù", definition: "six" },
  { traditional: "錢", simplified: "钱", pinyin: "qián", definition: "money" },
  { traditional: "點", simplified: "点", pinyin: "diǎn", definition: "point, dot" },
  { traditional: "十", simplified: "十", pinyin: "shí", definition: "ten" },
  { traditional: "您", simplified: "您", pinyin: "nín", definition: "you (polite)" },
  { traditional: "作", simplified: "作", pinyin: "zuò", definition: "do, make" },
  { traditional: "找", simplified: "找", pinyin: "zhǎo", definition: "look for" },
  { traditional: "見", simplified: "见", pinyin: "jiàn", definition: "see, meet" },
  { traditional: "半", simplified: "半", pinyin: "bàn", definition: "half" },
  { traditional: "帶", simplified: "带", pinyin: "dài", definition: "bring, carry" },
  { traditional: "件", simplified: "件", pinyin: "jiàn", definition: "item, piece" },
  { traditional: "下", simplified: "下", pinyin: "xià", definition: "below, under" },
  { traditional: "書", simplified: "书", pinyin: "shū", definition: "book" },
  { traditional: "自", simplified: "自", pinyin: "zì", definition: "self, from" },
  { traditional: "言", simplified: "言", pinyin: "yán", definition: "speech, words" },
  { traditional: "愛", simplified: "爱", pinyin: "ài", definition: "love" },
  { traditional: "手", simplified: "手", pinyin: "shǒu", definition: "hand" },
  { traditional: "打", simplified: "打", pinyin: "dǎ", definition: "hit, strike" },
  { traditional: "水", simplified: "水", pinyin: "shuǐ", definition: "water" },
  { traditional: "難", simplified: "难", pinyin: "nán", definition: "difficult" },
  { traditional: "買", simplified: "买", pinyin: "mǎi", definition: "buy" },
  { traditional: "寫", simplified: "写", pinyin: "xiě", definition: "write" },
  { traditional: "知", simplified: "知", pinyin: "zhī", definition: "know" },
  { traditional: "聽", simplified: "听", pinyin: "tīng", definition: "listen, hear" },
  { traditional: "吃", simplified: "吃", pinyin: "chī", definition: "eat" },
  { traditional: "心", simplified: "心", pinyin: "xīn", definition: "heart, mind" },
  { traditional: "家", simplified: "家", pinyin: "jiā", definition: "home, family" },
  { traditional: "四", simplified: "四", pinyin: "sì", definition: "four" },
  { traditional: "五", simplified: "五", pinyin: "wǔ", definition: "five" },
  { traditional: "二", simplified: "二", pinyin: "èr", definition: "two" },
];

// Example actors for Hanzi Movie Method initials
// Categories: Male (basic initials), Female (y-/i- initials), Fictional (w-/u- initials), World Leaders (ü initials)

export const exampleActors = [
  // MALE actors - initials: b-, p-, m-, f-, d-, t-, n-, l-, g-, k-, h-, zh-, ch-, sh-, r-, z-, c-, s-, Ø (null initial)
  { name: "Bobby Lee", initial: "b-", emoji: "🎬", category: "male", description: "Male actor - for b- sounds like bù, bèi, bǎ" },
  { name: "Pewdiepie", initial: "p-", emoji: "🎮", category: "male", description: "Male actor - for p- sounds like péngyou" },
  { name: "Mike Tyson", initial: "m-", emoji: "🥊", category: "male", description: "Male actor - for m- sounds like méi, měi, míng" },
  { name: "Pharrell", initial: "f-", emoji: "🦴", category: "male", description: "Male actor - for f- sounds like fēi" },
  { name: "Dave Chappelle", initial: "d-", emoji: "💪", category: "male", description: "Male actor - for d- sounds like dà, dào, dāng" },
  { name: "Tom Cruise", initial: "t-", emoji: "🧗‍♂️", category: "male", description: "Male actor - for t- sounds like tā, tiān, tīng" },
  { name: "Nicolas Cage", initial: "n-", emoji: "🐝", category: "male", description: "Male actor - for n- sounds like nà, néng, nián" },
  { name: "", initial: "l-", emoji: "", category: "male", description: "Male actor - for l- sounds like lái, liǎng, liù" },
  { name: "George W. Bush", initial: "g-", emoji: "☕", category: "male", description: "Male actor - for g- sounds like gè, gěi, gāo" },
  { name: "Keanu Reeves", initial: "k-", emoji: "🔫", category: "male", description: "Male actor - for k- sounds like kě, kàn" },
  { name: "Harrison Ford", initial: "h-", emoji: "🤠", category: "male", description: "Male actor - for h- sounds like hǎo, hái, huì" },
  { name: "Jimmy O Yang", initial: "zh-", emoji: "🧙", category: "male", description: "Male actor - for zh- sounds like zhè, zhōng, zhī" },
  { name: "Channing Tatum", initial: "ch-", emoji: "🎩", category: "male", description: "Male actor - for ch- sounds like chī, cháng" },
  { name: "Shohei Ohtani", initial: "sh-", emoji: "🏆", category: "male", description: "Male actor - for sh- sounds like shàng, shuō, shí" },
  { name: "Robert Downey Jr", initial: "r-", emoji: "🦾", category: "male", description: "Male actor - for r- sounds like rén, rú" },
  { name: "Zac Efron", initial: "z-", emoji: "🎤", category: "male", description: "Male actor - for z- sounds like zài, zuò, zǒu" },
  { name: "Chris Rock", initial: "c-", emoji: "🛡️", category: "male", description: "Male actor - for c- sounds like cóng, cái, cì" },
  { name: "iShow(Speed)", initial: "s-", emoji: "🐍", category: "male", description: "Male actor - for s- sounds like sān, suǒ, sì" },
  { name: "Arnold Schwarzenegger", initial: "Ø", emoji: "🤖", category: "male", description: "Male actor - for null initial (vowel-only) sounds like ài, àn, āo" },

  // FEMALE actors - initials: y-, bi-, pi-, mi-, di-, ti-, ji-, qi-, xi-, ni-, li-
  { name: "Michelle Yeoh", initial: "y-", emoji: "🌸", category: "female", description: "Female actor - for y- sounds like yī, yǒu, yào" },
  { name: "Billie Eilish", initial: "bi-", emoji: "👑", category: "female", description: "Female actor - for bi- sounds like bǐ" },
  { name: "Pink", initial: "pi-", emoji: "🎸", category: "female", description: "Female actor - for pi- sounds like piào" },
  { name: "Mina", initial: "mi-", emoji: "🎵", category: "female", description: "Female actor - for mi- sounds like míng" },
  { name: "Cyn(di) Lauper", initial: "di-", emoji: "💿", category: "female", description: "Female actor - for di- sounds like dì" },
  { name: "TEA (Tanya)", initial: "ti-", emoji: "⚡", category: "female", description: "Female actor - for ti- sounds like tiān" },
  { name: "Jisoo", initial: "ji-", emoji: "🥋", category: "female", description: "Female actor - for ji- sounds like jiù, jiā, jiàn" },
  { name: "Queen Latifah", initial: "qi-", emoji: "👸", category: "female", description: "Female actor - for qi- sounds like qǐng, qī" },
  { name: "Sta(cie)", initial: "xi-", emoji: "⚔️", category: "female", description: "Female actor - for xi- sounds like xiǎo, xīn, xiě" },
  { name: "Han(ni)", initial: "ni-", emoji: "🎬", category: "female", description: "Female actor - for ni- sounds like nǐ, nián" },
  { name: "Lisa", initial: "li-", emoji: "🎷", category: "female", description: "Female actor - for li- sounds like lǐ, liǎng" },

  // FICTIONAL characters - initials: w-, bu-, pu-, mu-, fu-, du-, tu-, nu-, lu-, zu-, cu-, su-, zhu-, chu-, shu-, ru-, ku-, hu-, gu-
  { name: "Walter White", initial: "w-", emoji: "🧪", category: "fictional", description: "Fictional - for w- sounds like wǒ, wéi, wèn" },
  { name: "Bugs Bunny", initial: "bu-", emoji: "🐰", category: "fictional", description: "Fictional - for bu- sounds like bù" },
  { name: "Pooh Bear", initial: "pu-", emoji: "🐻", category: "fictional", description: "Fictional - for pu- sounds like pú" },
  { name: "Mulan", initial: "mu-", emoji: "⚔️", category: "fictional", description: "Fictional - for mu- sounds like mù, mǔ" },
  { name: "Kung (Fu) Panda", initial: "fu-", emoji: "🌸", category: "fictional", description: "Fictional - for fu- sounds like fù, fú" },
  { name: "Duke Nukem", initial: "du-", emoji: "🐘", category: "fictional", description: "Fictional - for du- sounds like dù, dú" },
  { name: "Tupac", initial: "tu-", emoji: "🐧", category: "fictional", description: "Fictional - for tu- sounds like tú, tǔ" },
  { name: "Nutty Professor", initial: "nu-", emoji: "🦁", category: "fictional", description: "Fictional - for nu- sounds like nǔ, nù" },
  { name: "Luke Skywalker", initial: "lu-", emoji: "⚔️", category: "fictional", description: "Fictional - for lu- sounds like lù, lǔ" },
  { name: "Zuko", initial: "zu-", emoji: "🔥", category: "fictional", description: "Fictional - for zu- sounds like zǔ, zú" },
  { name: "Cuphead", initial: "cu-", emoji: "☕", category: "fictional", description: "Fictional - for cu- sounds like cù, cú" },
  { name: "Super Mario", initial: "su-", emoji: "🍄", category: "fictional", description: "Fictional - for su- sounds like sù, sú" },
  { name: "Piglet", initial: "zhu-", emoji: "🐷", category: "fictional", description: "Fictional - for zhu- sounds like zhù, zhū" },
  { name: "Pika(chu)", initial: "chu-", emoji: "🔪", category: "fictional", description: "Fictional - for chu- sounds like chū, chú" },
  { name: "Mu(shu)", initial: "shu-", emoji: "⚔️", category: "fictional", description: "Fictional - for shu- sounds like shū, shù" },
  { name: "Rufio", initial: "ru-", emoji: "👊", category: "fictional", description: "Fictional - for ru- sounds like rù, rú" },
  { name: "A(ku)ma", initial: "ku-", emoji: "🦊", category: "fictional", description: "Fictional - for ku- sounds like kù, kǔ" },
  { name: "Hulk", initial: "hu-", emoji: "💚", category: "fictional", description: "Fictional - for hu- sounds like hù, hú" },
  { name: "Forrest (Gu)mp", initial: "gu-", emoji: "🐉", category: "fictional", description: "Fictional - for gu- sounds like gù, gú" },

  // BASKETBALL PLAYERS - initials: yu-, nü-, lü-, ju-, qu-, xu-
  { name: "Yao Ming", initial: "yu-", emoji: "🏛️", category: "world_leader", description: "World leader - for yu- sounds like yuán, yuè" },
  { name: "Ma(nu) Ginobili", initial: "nü-", emoji: "🌍", category: "world_leader", description: "World leader - for nü- sounds like nǚ" },
  { name: "Skip to my (Lu)", initial: "lü-", emoji: "🗡️", category: "world_leader", description: "World leader - for lü- sounds like lǜ, lǚ" },
  { name: "Julius Erving", initial: "ju-", emoji: "🏛️", category: "world_leader", description: "World leader - for ju- sounds like jù, jǔ" },
  { name: "Sha(qu)ille O'Neal", initial: "qu-", emoji: "👑", category: "world_leader", description: "World leader - for qu- sounds like qù, qǔ" },
  { name: "Sue Bird", initial: "xu-", emoji: "🇨🇳", category: "world_leader", description: "World leader - for xu- sounds like xǔ, xù" },
];

// Example rooms for each tone
export const exampleRooms = [
  { name: "Bathroom", tone: 1, emoji: "🚿", description: "Tone 1 (high level ā) - You go to the bathroom in the morning, waking up" },
  { name: "Kitchen", tone: 2, emoji: "🍽️", description: "Tone 2 (rising á) - After you get up you go to the kitchen to eat breakfast, energy rises" },
  { name: "Office", tone: 3, emoji: "👨🏻‍💻", description: "Tone 3 (dipping ǎ) - You use up your energy at work and look forward to going home, energy goes down before going back up" },
  { name: "Bedroom", tone: 4, emoji: "🛌", description: "Tone 4 (falling à) - You're tired after a long day, energy falls" },
  { name: "Dream land", tone: 5, emoji: "💤", description: "Tone 5 (neutral a) - You're asleep, neutral feeling" },
];

// Example sets for HMM finals: -a, -ai, -ao, -an, -ang, -o, -ong, -ou, -e, -ei, -(e)n, -(e)ng
export const exampleSets = [
  { name: "Australia", final: "-a", emoji: "🦘", description: "For -a finals (tā, nà, dà, mā)" },
  { name: "Chiang Mai", final: "-ai", emoji: "🐘", description: "For -ai finals (lái, mǎi, dài, ài)" },
  { name: "Macau", final: "-ao", emoji: "🎰", description: "For -ao finals (hǎo, dào, gāo, zǎo)" },
  { name: "Xi'an", final: "-an", emoji: "🏯", description: "For -an finals (sān, nán, kàn, fàn)" },
  { name: "Shanghai", final: "-ang", emoji: "🥟", description: "For -ang finals (shàng, cháng, dāng, fáng)" },
  { name: "Kuala Lumpur", final: "-o", emoji: "🗼", description: "For -o finals (wǒ, bō, pō, mō)" },
  { name: "Hong Kong", final: "-ong", emoji: "🌸", description: "For -ong finals (zhōng, dōng, tóng, gōng)" },
  { name: "Seoul", final: "-ou", emoji: "🫰", description: "For -ou finals (dōu, zǒu, gǒu, hòu)" },
  { name: "Osaka", final: "-e", emoji: "⛩", description: "For -e finals (hé, gē, lè, dé)" },
  { name: "Beijing", final: "-ei", emoji: "🏛️", description: "For -ei finals (měi, bèi, fēi, gěi)" },
  { name: "Shenzhen", final: "-(e)n", emoji: "🤖", description: "For -(e)n finals (rén, hěn, shén, mén) - 'en' after most, 'n' after i/ü" },
  { name: "Chengdu", final: "-(e)ng", emoji: "🐼", description: "For -(e)ng finals (néng, shēng, míng, tīng) - 'eng' after most, 'ng' after i" },
];

// Example props for common radicals/components
export const exampleProps = [
  { name: "Person (standing)", component: "亻", description: "Standing person radical" },
  { name: "Person (sitting)", component: "人", description: "Person character as component" },
  { name: "Mouth", component: "口", description: "Mouth/opening radical" },
  { name: "Heart", component: "心", description: "Heart radical (bottom)" },
  { name: "Heart (side)", component: "忄", description: "Heart radical (left side)" },
  { name: "Hand", component: "手", description: "Hand character" },
  { name: "Hand (side)", component: "扌", description: "Hand radical (left side)" },
  { name: "Water", component: "水", description: "Water character" },
  { name: "Water (side)", component: "氵", description: "Water radical (left side)" },
  { name: "Fire", component: "火", description: "Fire character" },
  { name: "Fire (bottom)", component: "灬", description: "Fire radical (bottom)" },
  { name: "Wood/Tree", component: "木", description: "Wood/tree radical" },
  { name: "Sun", component: "日", description: "Sun radical" },
  { name: "Moon", component: "月", description: "Moon radical" },
  { name: "Speech", component: "言", description: "Speech character" },
  { name: "Speech (side)", component: "讠", description: "Speech radical (simplified)" },
  { name: "Walk", component: "辶", description: "Walking radical" },
  { name: "Earth", component: "土", description: "Earth/ground radical" },
  { name: "Woman", component: "女", description: "Woman radical" },
  { name: "Child", component: "子", description: "Child radical" },
  { name: "Big", component: "大", description: "Big/large radical" },
  { name: "Small", component: "小", description: "Small radical" },
  { name: "Eye", component: "目", description: "Eye radical" },
  { name: "Roof", component: "宀", description: "Roof/house radical" },
  { name: "Grass", component: "艹", description: "Grass radical (top)" },
  { name: "Metal", component: "金", description: "Metal/gold radical" },
  { name: "Metal (side)", component: "钅", description: "Metal radical (simplified)" },
  { name: "Food", component: "食", description: "Food/eat radical" },
  { name: "Food (side)", component: "饣", description: "Food radical (simplified)" },
  { name: "Knife", component: "刀", description: "Knife character" },
  { name: "Knife (side)", component: "刂", description: "Knife radical (right side)" },
  { name: "Strength", component: "力", description: "Strength/power radical" },
  { name: "One", component: "一", description: "One horizontal stroke" },
  { name: "Two", component: "二", description: "Two horizontal strokes" },
  { name: "Three", component: "三", description: "Three horizontal strokes" },
];
